name: Check Squash Commits

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-squash-commits:
    runs-on: ubuntu-latest
    name: Check commits are squashed
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check commits are squashed
        run: |
          # Get the commit range for the pull request
          COMMIT_RANGE="${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}"
          
          # Check if any commit in the range is not a squash commit
          COMMITS_NOT_SQUASHED=$(git log --format=%s $COMMIT_RANGE | grep -v '^\(sparkles\|bug\|book\|memo\|warning\|seedling\|question\)(\(.*\)): ')
          if [[ $COMMITS_NOT_SQUASHED ]]; then
            echo "Error: The following commit(s) in this PR has not been squashed: "
            echo "$COMMITS_NOT_SQUASHED"
            exit 1
          fi
